version: "3.7"

services:
  sample-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: normal_user
      POSTGRES_DB: cool_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "6432:5432"
    volumes:
      - pg-lineage:/var/lib/postgresql/data

volumes:
  pg-lineage:
