on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.7.2
        id: release
        with:
          # use the CI token to pretend not to be a action
          token: ${{ secrets.CONTIAMO_CI_TOKEN }}
          release-type: python
          package-name: ""
          bump-minor-pre-major: true
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"docs","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Miscellaneous","hidden":false}
            ]

      - name: Debug release output
        env:
          OUTPUTS: ${{ toJSON(steps.release.outputs) }}
        run: echo '$OUTPUTS'
